### ISSUE TITLE
Choice of template / build & test system

### ISSUE THREAD

**Issue by mhvk** [astropy/quantity-2.0#1]
@adrn, @jeffjennings, @nstarman - I have a branch with a minimal working Quantity ready to push, but realized I'm held back by the setup of this new package being very unlike that of astropy, with, e.g., no support for `setuptools` and `tox`, but instead (I think) `hatch`. Is this on purpose? Is there any advantage large enough to overcome the cost of me having to learn yet another tool? 

Any objection to just restarting with the OpenAstronomy packaging guide? That way I know how to set up github CI, etc. With another tool, it is probably better if someone else does it.

p.s.  Sorry for grumpiness, but I just spent about 1 hour (= US$150) with no progress to show for it; `hatch` is not even available on Debian, unlike `tox`, and has had no commits in the last 2 years...

**Comment by jeffjennings** [comment]
I have no objection, whatever's easiest to keep things moving seems best to me.

**Comment by jeffjennings** [comment]
I have no objection, whatever's easiest to keep things moving seems best to
me.

**Comment by mhvk** [comment]
OK, went ahead and force-pushed the openastronomy template. I also made a first PR with actual implementation - see #2 (though still working on seeing whether the ufuncs work with dask/jax).
