### ISSUE TITLE
Use walled-garden approach

### ISSUE THREAD

**Issue by nstarman** [astropy/quantity-2.0#9]
The following approach allows for very exact control over the public API while also making devs' lives easy with a full private API and non-prefix-underscored file names.

```
src/
    quantity/
        __init__.py  # defines the public API
        api.py  # e.g. a public module with public API that contains the API protocols.
        _src/  # private API walled garden. Everything here is private and easily worked on by devs w/out public API consequences.
            base.py  # named whatever we want. no pre-fix underscores.
            core.py  # named whatever we want. no pre-fix underscores.
            api.py  # named whatever we want. no pre-fix underscores.
            errors.py  # named whatever we want. no pre-fix underscores.
```

`__init__.py` and the example `api.py` are very simple modules that define the public API. For example

```
# __init__.py
"""User-facing docstring for quantity package"""

__all__ = ["AbstractQuantity", "Quantity", ...]

from ._src.base import AbstractQuantity
from ._src.core import Quantity
```

```
# api.py
"""User-facing docstring for quantity.api module"""

__all__ = ["Quantity", "ArrayQuantity"]

from ._src.api import Quantity, ArrayQuantity
```

Check out https://github.com/GalacticDynamics/unxt/tree/main/src/unxt, where I've implemented this code pattern. It's worked **wonderfully**. The API is 100% clear and 100% complies with PEP 8 standards — a great benefit individually and synergistically for users, developers, and code tools. With just one underscore-prefixed module this pattern completely separates public from private API and makes life very easy for developers who never need to worry about moving classes, renaming / deleting files. Private files  also aren't themselves underscore-prefixed, which is a major bonus. Another bonus is that the `__all__` in the private modules can define a private API, e.g. functions that are marked for use in other private modules, but not in the public API, which has its own clear definition.

**Comment by mhvk** [comment]
I am happy to go with this; certainly like the idea that the code proper does not have to worry about underscores at all. But the double `src` seems a bit excessive...

**Comment by mhvk** [comment]
Darn, I look again and start doubting: I like this approach, but it does seem to have all the advantages of a source layout on its own too...
